server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bootcamp_2510p
    username: postgres
    password: Admin1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect   # tell hibernate to use postgreSQL dialect
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
  
app:
  provider:
    base-url: http://localhost:8081
    datatype:
      profile: company
      quote: quote


management:
  endpoints:
    web:
      exposure:
        include: health,info
