server:
  port: 8081


finnhub:
  data: 
    domain: "finnhub.io"
    path: "/api/v1/"
    quote: "quote"
    profile: "stock/profile2"
    query:
      token: "d6o0uh9r01qsfaqqjv40d6o0uh9r01qsfaqqjv4g"
    
