FROM amazoncorretto:21
ADD target/project-stock-data-0.0.1-SNAPSHOT.jar project-stock-data-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java", "-jar","project-stock-data-0.0.1-SNAPSHOT.jar"]  
EXPOSE 8181

# entrypoint: run java, execute jar file
